import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { AddToCart, deleteToCart, getCartItems, updateToCart } from './CartApi';

const initialState = {
  cartItems: null

};
export const addToCartAsync = createAsyncThunk(
  'cart/addItem',
  async (product) => {
    console.log(product,"product deails")
    const response = await AddToCart(product);
    return response
  }
);
export const getAllCartItemsAsync = createAsyncThunk(
  'cart/getItems',
  async (userId) => {

    const response = await getCartItems (userId);
    return response
  }
);
export const updateQuantityAsync = createAsyncThunk(
  'cart/updateItem',
  async (data) => {
    const response = await updateToCart(data);
    // The value we return becomes the `fulfilled` action payload
    return response;
  }
);

export const deleteToCartAsync = createAsyncThunk(
  'cart/deleteProduct',
  async (cartId) => {
    console.log(cartId,"cart id")
    const response = await deleteToCart(cartId);
    return response;
  }
);


export const cartSlice = createSlice({
  name: 'Cart',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    incrementQuantity: (state) => {
      const updatedCartItems = state.cartItems.map(item =>
        item[0].id === id
          ? { ...item[0], quantity: item[0].quantity + 1 } // Update quantity for the matching item
          : item[0]
      );
      state.cartItems = updatedCartItems;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(addToCartAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(deleteToCartAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(addToCartAsync.fulfilled, (state, action) => {
        state.status = 'idle';
      })
      .addCase(getAllCartItemsAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.cartItems = action.payload
      })
      .addCase(deleteToCartAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.cartItems.map(item => item.id !== action.payload)
      })

  },
});

export const { incrementQuantity } = cartSlice.actions;


export default cartSlice.reducer;